#ifndef _CONFIG_H_
#define _CONFIG_H_

#define CLK_DEINIT
#define CLK_SYSCLKCONFIG
#define CLK_CLOCKSWITCHCMD
#define CLK_CLOCKSWITCHCONFIG
#define CLK_HSECMD
#define CLK_HSICMD
#define CLK_LSICMD
#define CLK_GETCLOCKFREQ
#define CLK_HSIPRESCALERCONFIG
#define CLK_GETFLAGSTATUS
#define CLK_PERIPHERALCLOCKCONFIG
#define CLK_CLOCKSWITCHCMD

#define GPIO_DEINIT
#define GPIO_INIT
#define GPIO_WRITELOW
#define GPIO_WRITEHIGH
#define GPIO_WRITEREVERCE
#define GPIO_READINPUTPIN

#define UART2_DEINIT
#define UART2_INIT
#define UART2_CMD
#define UART2_GETFLAGSTATUS
#define UART2_ITCONFIG
#define UART2_SENDDATA8
#define UART2_RECEIVEDATA8
#define UART2_RECEIVERWAKEUPCMD

#define AWU_DEINIT
#define AWU_INIT
#define AWU_CMD
// #define AWU_LSICALIBRATIONCONFIG
// #define AWU_IDLEMODEENABLE
#define AWU_GETFLAGSTATUS

#define I2C_INIT
#define I2C_CMD
#define I2C_SENDDATA
#define I2C_SEND7BITADDRESS
#define I2C_GETFLAGSTATUS
#define I2C_CHECKEVENT
#define I2C_GENERATESTOP
#define I2C_GENERATESTART
#define I2C_ACKNOWLEDGECONFIG
#define I2C_ACKNOWLEDGECONFIG
#define I2C_RECEIVEDATA

#endif